(cl:in-package quadrotor_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          AUTOPILOT_STATE-VAL
          AUTOPILOT_STATE
          CONTROL_COMMAND_DELAY-VAL
          CONTROL_COMMAND_DELAY
          CONTROL_COMPUTATION_TIME-VAL
          CONTROL_COMPUTATION_TIME
          TRAJECTORY_EXECUTION_LEFT_DURATION-VAL
          TRAJECTORY_EXECUTION_LEFT_DURATION
          TRAJECTORIES_LEFT_IN_QUEUE-VAL
          TRAJECTORIES_LEFT_IN_QUEUE
          LOW_LEVEL_FEEDBACK-VAL
          LOW_LEVEL_FEEDBACK
          REFERENCE_STATE-VAL
          REFERENCE_STATE
          STATE_ESTIMATE-VAL
          STATE_ESTIMATE
))