(cl:defpackage quadrotor_msgs-msg
  (:use )
  (:export
   "<AUTOPILOTFEEDBACK>"
   "AUTOPILOTFEEDBACK"
   "<CONTROLCOMMAND>"
   "CONTROLCOMMAND"
   "<LOWLEVELFEEDBACK>"
   "LOWLEVELFEEDBACK"
   "<POSITIONCOMMAND>"
   "POSITIONCOMMAND"
   "<TRAJECTORY>"
   "TRAJECTORY"
   "<TRAJECTORYPOINT>"
   "TRAJECTORYPOINT"
  ))

