set(_CATKIN_CURRENT_PACKAGE "lkh_tsp_solver")
set(lkh_tsp_solver_VERSION "0.0.0")
set(lkh_tsp_solver_MAINTAINER "bzhouai <bzhouai@todo.todo>")
set(lkh_tsp_solver_PACKAGE_FORMAT "2")
set(lkh_tsp_solver_BUILD_DEPENDS "roscpp")
set(lkh_tsp_solver_BUILD_EXPORT_DEPENDS "roscpp")
set(lkh_tsp_solver_BUILDTOOL_DEPENDS "catkin")
set(lkh_tsp_solver_BUILDTOOL_EXPORT_DEPENDS )
set(lkh_tsp_solver_EXEC_DEPENDS "roscpp")
set(lkh_tsp_solver_RUN_DEPENDS "roscpp")
set(lkh_tsp_solver_TEST_DEPENDS )
set(lkh_tsp_solver_DOC_DEPENDS )
set(lkh_tsp_solver_URL_WEBSITE "")
set(lkh_tsp_solver_URL_BUGTRACKER "")
set(lkh_tsp_solver_URL_REPOSITORY "")
set(lkh_tsp_solver_DEPRECATED "")