set(_CATKIN_CURRENT_PACKAGE "exploration_manager")
set(exploration_manager_VERSION "0.0.0")
set(exploration_manager_MAINTAINER "bzhouai <bzhouai@todo.todo>")
set(exploration_manager_PACKAGE_FORMAT "2")
set(exploration_manager_BUILD_DEPENDS "roscpp" "std_msgs" "plan_env" "path_searching" "bspline" "bspline_opt" "active_perception" "traj_utils" "lkh_tsp_solver" "plan_manage" "quadrotor_msgs")
set(exploration_manager_BUILD_EXPORT_DEPENDS "roscpp" "std_msgs")
set(exploration_manager_BUILDTOOL_DEPENDS "catkin")
set(exploration_manager_BUILDTOOL_EXPORT_DEPENDS )
set(exploration_manager_EXEC_DEPENDS "roscpp" "std_msgs" "plan_env" "path_searching" "bspline" "bspline_opt" "active_perception" "traj_utils" "lkh_tsp_solver" "plan_manage" "quadrotor_msgs")
set(exploration_manager_RUN_DEPENDS "roscpp" "std_msgs" "plan_env" "path_searching" "bspline" "bspline_opt" "active_perception" "traj_utils" "lkh_tsp_solver" "plan_manage" "quadrotor_msgs")
set(exploration_manager_TEST_DEPENDS )
set(exploration_manager_DOC_DEPENDS )
set(exploration_manager_URL_WEBSITE "")
set(exploration_manager_URL_BUGTRACKER "")
set(exploration_manager_URL_REPOSITORY "")
set(exploration_manager_DEPRECATED "")