set(_CATKIN_CURRENT_PACKAGE "ground_station")
set(ground_station_VERSION "0.0.0")
set(ground_station_MAINTAINER "ze wang <w407022008@gmail.com>")
set(ground_station_PACKAGE_FORMAT "2")
set(ground_station_BUILD_DEPENDS "message_generation" "std_msgs")
set(ground_station_BUILD_EXPORT_DEPENDS "std_msgs")
set(ground_station_BUILDTOOL_DEPENDS "catkin")
set(ground_station_BUILDTOOL_EXPORT_DEPENDS )
set(ground_station_EXEC_DEPENDS "message_runtime" "std_msgs")
set(ground_station_RUN_DEPENDS "message_runtime" "std_msgs")
set(ground_station_TEST_DEPENDS )
set(ground_station_DOC_DEPENDS )
set(ground_station_URL_WEBSITE "")
set(ground_station_URL_BUGTRACKER "")
set(ground_station_URL_REPOSITORY "")
set(ground_station_DEPRECATED "")