set(_CATKIN_CURRENT_PACKAGE "drone_msgs")
set(drone_msgs_VERSION "0.0.0")
set(drone_msgs_MAINTAINER "ze wang <w407022009@gmail.com>")
set(drone_msgs_PACKAGE_FORMAT "2")
set(drone_msgs_BUILD_DEPENDS "message_generation" "std_msgs" "actionlib_msgs" "geometry_msgs" "sensor_msgs" "mavros_msgs")
set(drone_msgs_BUILD_EXPORT_DEPENDS "std_msgs" "actionlib_msgs" "geometry_msgs" "sensor_msgs" "mavros_msgs")
set(drone_msgs_BUILDTOOL_DEPENDS "catkin")
set(drone_msgs_BUILDTOOL_EXPORT_DEPENDS )
set(drone_msgs_EXEC_DEPENDS "message_runtime" "std_msgs" "actionlib_msgs" "geometry_msgs" "sensor_msgs" "mavros_msgs")
set(drone_msgs_RUN_DEPENDS "message_runtime" "std_msgs" "actionlib_msgs" "geometry_msgs" "sensor_msgs" "mavros_msgs")
set(drone_msgs_TEST_DEPENDS )
set(drone_msgs_DOC_DEPENDS )
set(drone_msgs_URL_WEBSITE "")
set(drone_msgs_URL_BUGTRACKER "")
set(drone_msgs_URL_REPOSITORY "")
set(drone_msgs_DEPRECATED "")