set(_CATKIN_CURRENT_PACKAGE "mavros_interface")
set(mavros_interface_VERSION "0.0.0")
set(mavros_interface_MAINTAINER "Ze <w407022008@gmail.com>")
set(mavros_interface_PACKAGE_FORMAT "2")
set(mavros_interface_BUILD_DEPENDS "message_generation" "roscpp" "rospy" "std_msgs" "sensor_msgs" "geometry_msgs" "nav_msgs" "drone_msgs" "pcl_ros" "pcl_conversions" "libpcl-all-dev" "quadrotor_common")
set(mavros_interface_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs" "sensor_msgs" "geometry_msgs" "nav_msgs" "drone_msgs" "quadrotor_common")
set(mavros_interface_BUILDTOOL_DEPENDS "catkin")
set(mavros_interface_BUILDTOOL_EXPORT_DEPENDS )
set(mavros_interface_EXEC_DEPENDS "message_runtime" "roscpp" "rospy" "std_msgs" "sensor_msgs" "geometry_msgs" "nav_msgs" "drone_msgs" "pcl_ros" "pcl_conversions" "libpcl-all" "quadrotor_common")
set(mavros_interface_RUN_DEPENDS "message_runtime" "roscpp" "rospy" "std_msgs" "sensor_msgs" "geometry_msgs" "nav_msgs" "drone_msgs" "pcl_ros" "pcl_conversions" "libpcl-all" "quadrotor_common")
set(mavros_interface_TEST_DEPENDS )
set(mavros_interface_DOC_DEPENDS )
set(mavros_interface_URL_WEBSITE "")
set(mavros_interface_URL_BUGTRACKER "")
set(mavros_interface_URL_REPOSITORY "")
set(mavros_interface_DEPRECATED "")