(cl:in-package mavros_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          SENSORS_PRESENT-VAL
          SENSORS_PRESENT
          SENSORS_ENABLED-VAL
          SENSORS_ENABLED
          SENSORS_HEALTH-VAL
          SENSORS_HEALTH
          LOAD-VAL
          LOAD
          VOLTAGE_BATTERY-VAL
          VOLTAGE_BATTERY
          CURRENT_BATTERY-VAL
          CURRENT_BATTERY
          BATTERY_REMAINING-VAL
          BATTERY_REMAINING
          DROP_RATE_COMM-VAL
          DROP_RATE_COMM
          ERRORS_COMM-VAL
          ERRORS_COMM
          ERRORS_COUNT1-VAL
          ERRORS_COUNT1
          ERRORS_COUNT2-VAL
          ERRORS_COUNT2
          ERRORS_COUNT3-VAL
          ERRORS_COUNT3
          ERRORS_COUNT4-VAL
          ERRORS_COUNT4
))