# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from drone_msgs/AttitudeReference.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import std_msgs.msg

class AttitudeReference(genpy.Message):
  _md5sum = "ad65c8727b64e262c550df8ad8b37905"
  _type = "drone_msgs/AttitudeReference"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """std_msgs/Header header

## Setpoint Attitude + T
float32[3] thrust_sp                   ## Single Rotor Thrust setpoint
float32 collective_accel               ## [m/s^2] Axis Body_Z Collective accel septoint
float32[3] desired_attitude            ## [rad] Eurler angle setpoint
geometry_msgs/Quaternion desired_att_q ## quat setpoint
geometry_msgs/Vector3 body_rate  ## [rad/s]

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id

================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w

================================================================================
MSG: geometry_msgs/Vector3
# This represents a vector in free space. 
# It is only meant to represent a direction. Therefore, it does not
# make sense to apply a translation to it (e.g., when applying a 
# generic rigid transformation to a Vector3, tf2 will only apply the
# rotation). If you want your data to be translatable too, use the
# geometry_msgs/Point message instead.

float64 x
float64 y
float64 z"""
  __slots__ = ['header','thrust_sp','collective_accel','desired_attitude','desired_att_q','body_rate']
  _slot_types = ['std_msgs/Header','float32[3]','float32','float32[3]','geometry_msgs/Quaternion','geometry_msgs/Vector3']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,thrust_sp,collective_accel,desired_attitude,desired_att_q,body_rate

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(AttitudeReference, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.thrust_sp is None:
        self.thrust_sp = [0.] * 3
      if self.collective_accel is None:
        self.collective_accel = 0.
      if self.desired_attitude is None:
        self.desired_attitude = [0.] * 3
      if self.desired_att_q is None:
        self.desired_att_q = geometry_msgs.msg.Quaternion()
      if self.body_rate is None:
        self.body_rate = geometry_msgs.msg.Vector3()
    else:
      self.header = std_msgs.msg.Header()
      self.thrust_sp = [0.] * 3
      self.collective_accel = 0.
      self.desired_attitude = [0.] * 3
      self.desired_att_q = geometry_msgs.msg.Quaternion()
      self.body_rate = geometry_msgs.msg.Vector3()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      buff.write(_get_struct_3f().pack(*self.thrust_sp))
      _x = self.collective_accel
      buff.write(_get_struct_f().pack(_x))
      buff.write(_get_struct_3f().pack(*self.desired_attitude))
      _x = self
      buff.write(_get_struct_7d().pack(_x.desired_att_q.x, _x.desired_att_q.y, _x.desired_att_q.z, _x.desired_att_q.w, _x.body_rate.x, _x.body_rate.y, _x.body_rate.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.desired_att_q is None:
        self.desired_att_q = geometry_msgs.msg.Quaternion()
      if self.body_rate is None:
        self.body_rate = geometry_msgs.msg.Vector3()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      start = end
      end += 12
      self.thrust_sp = _get_struct_3f().unpack(str[start:end])
      start = end
      end += 4
      (self.collective_accel,) = _get_struct_f().unpack(str[start:end])
      start = end
      end += 12
      self.desired_attitude = _get_struct_3f().unpack(str[start:end])
      _x = self
      start = end
      end += 56
      (_x.desired_att_q.x, _x.desired_att_q.y, _x.desired_att_q.z, _x.desired_att_q.w, _x.body_rate.x, _x.body_rate.y, _x.body_rate.z,) = _get_struct_7d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      buff.write(self.thrust_sp.tostring())
      _x = self.collective_accel
      buff.write(_get_struct_f().pack(_x))
      buff.write(self.desired_attitude.tostring())
      _x = self
      buff.write(_get_struct_7d().pack(_x.desired_att_q.x, _x.desired_att_q.y, _x.desired_att_q.z, _x.desired_att_q.w, _x.body_rate.x, _x.body_rate.y, _x.body_rate.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.desired_att_q is None:
        self.desired_att_q = geometry_msgs.msg.Quaternion()
      if self.body_rate is None:
        self.body_rate = geometry_msgs.msg.Vector3()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      start = end
      end += 12
      self.thrust_sp = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=3)
      start = end
      end += 4
      (self.collective_accel,) = _get_struct_f().unpack(str[start:end])
      start = end
      end += 12
      self.desired_attitude = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=3)
      _x = self
      start = end
      end += 56
      (_x.desired_att_q.x, _x.desired_att_q.y, _x.desired_att_q.z, _x.desired_att_q.w, _x.body_rate.x, _x.body_rate.y, _x.body_rate.z,) = _get_struct_7d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_3f = None
def _get_struct_3f():
    global _struct_3f
    if _struct_3f is None:
        _struct_3f = struct.Struct("<3f")
    return _struct_3f
_struct_7d = None
def _get_struct_7d():
    global _struct_7d
    if _struct_7d is None:
        _struct_7d = struct.Struct("<7d")
    return _struct_7d
_struct_f = None
def _get_struct_f():
    global _struct_f
    if _struct_f is None:
        _struct_f = struct.Struct("<f")
    return _struct_f
