set(_CATKIN_CURRENT_PACKAGE "quadrotor_common")
set(quadrotor_common_VERSION "0.0.0")
set(quadrotor_common_MAINTAINER "Matthias Faessler <faessler@ifi.uzh.ch>")
set(quadrotor_common_PACKAGE_FORMAT "2")
set(quadrotor_common_BUILD_DEPENDS "eigen_catkin" "geometry_msgs" "nav_msgs" "quadrotor_msgs" "roscpp")
set(quadrotor_common_BUILD_EXPORT_DEPENDS "eigen_catkin" "geometry_msgs" "nav_msgs" "quadrotor_msgs" "roscpp")
set(quadrotor_common_BUILDTOOL_DEPENDS "catkin" "catkin_simple")
set(quadrotor_common_BUILDTOOL_EXPORT_DEPENDS )
set(quadrotor_common_EXEC_DEPENDS "eigen_catkin" "geometry_msgs" "nav_msgs" "quadrotor_msgs" "roscpp")
set(quadrotor_common_RUN_DEPENDS "eigen_catkin" "geometry_msgs" "nav_msgs" "quadrotor_msgs" "roscpp")
set(quadrotor_common_TEST_DEPENDS )
set(quadrotor_common_DOC_DEPENDS )
set(quadrotor_common_URL_WEBSITE "")
set(quadrotor_common_URL_BUGTRACKER "")
set(quadrotor_common_URL_REPOSITORY "")
set(quadrotor_common_DEPRECATED "")