(cl:defpackage drone_msgs-msg
  (:use )
  (:export
   "<ARDUINO>"
   "ARDUINO"
   "<ATTITUDEREFERENCE>"
   "ATTITUDEREFERENCE"
   "<BSPLINE>"
   "BSPLINE"
   "<CONTROLCOMMAND>"
   "CONTROLCOMMAND"
   "<CONTROLOUTPUT>"
   "CONTROLOUTPUT"
   "<DRONESTATE>"
   "DRONESTATE"
   "<DRONETARGET>"
   "DRONETARGET"
   "<MESSAGE>"
   "MESSAGE"
   "<POSITIONREFERENCE>"
   "POSITIONREFERENCE"
   "<RCINPUT>"
   "RCINPUT"
  ))

