## parameter for px4_commander.cpp

Takeoff_height : 1.0
Land_speed : 0.2
Disarm_height : 0.12

Command_rate : 50.0

geo_fence:
  x_min: -50
  x_max: 50
  y_min: -50
  y_max: 50
  z_min: -0.5
  z_max: 50
