(cl:in-package drone_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          MESSAGE_TYPE-VAL
          MESSAGE_TYPE
          AIRFLOW_SENSOR_NUM-VAL
          AIRFLOW_SENSOR_NUM
          CURRENT-VAL
          CURRENT
          VOLTAGE-VAL
          VOLTAGE
          POWER-VAL
          POWER
          POW_DIFF-VAL
          POW_DIFF
          DIFF_VOLT-VAL
          DIFF_VOLT
          QUATERNION-VAL
          QUATERNION
          EULAR_ANGLE-VAL
          EULAR_ANGLE
          ACC-VAL
          ACC
          MAG-VAL
          MAG
          GYRO-VAL
          GYRO
          BARO-VAL
          BARO
          TEMP-VAL
          TEMP
))