// Generated by gencpp from file drone_msgs/PositionReference.msg
// DO NOT EDIT!


#ifndef DRONE_MSGS_MESSAGE_POSITIONREFERENCE_H
#define DRONE_MSGS_MESSAGE_POSITIONREFERENCE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <drone_msgs/Bspline.h>

namespace drone_msgs
{
template <class ContainerAllocator>
struct PositionReference_
{
  typedef PositionReference_<ContainerAllocator> Type;

  PositionReference_()
    : header()
    , Move_mode(0)
    , Move_frame(0)
    , time_from_start(0.0)
    , position_ref()
    , velocity_ref()
    , acceleration_ref()
    , Yaw_Rate_Mode(false)
    , yaw_ref(0.0)
    , yaw_rate_ref(0.0)
    , bspline()  {
      position_ref.assign(0.0);

      velocity_ref.assign(0.0);

      acceleration_ref.assign(0.0);
  }
  PositionReference_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , Move_mode(0)
    , Move_frame(0)
    , time_from_start(0.0)
    , position_ref()
    , velocity_ref()
    , acceleration_ref()
    , Yaw_Rate_Mode(false)
    , yaw_ref(0.0)
    , yaw_rate_ref(0.0)
    , bspline(_alloc)  {
  (void)_alloc;
      position_ref.assign(0.0);

      velocity_ref.assign(0.0);

      acceleration_ref.assign(0.0);
  }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _Move_mode_type;
  _Move_mode_type Move_mode;

   typedef uint8_t _Move_frame_type;
  _Move_frame_type Move_frame;

   typedef float _time_from_start_type;
  _time_from_start_type time_from_start;

   typedef boost::array<float, 3>  _position_ref_type;
  _position_ref_type position_ref;

   typedef boost::array<float, 3>  _velocity_ref_type;
  _velocity_ref_type velocity_ref;

   typedef boost::array<float, 3>  _acceleration_ref_type;
  _acceleration_ref_type acceleration_ref;

   typedef uint8_t _Yaw_Rate_Mode_type;
  _Yaw_Rate_Mode_type Yaw_Rate_Mode;

   typedef float _yaw_ref_type;
  _yaw_ref_type yaw_ref;

   typedef float _yaw_rate_ref_type;
  _yaw_rate_ref_type yaw_rate_ref;

   typedef  ::drone_msgs::Bspline_<ContainerAllocator>  _bspline_type;
  _bspline_type bspline;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(XYZ_POS)
  #undef XYZ_POS
#endif
#if defined(_WIN32) && defined(XY_POS_Z_VEL)
  #undef XY_POS_Z_VEL
#endif
#if defined(_WIN32) && defined(XY_VEL_Z_POS)
  #undef XY_VEL_Z_POS
#endif
#if defined(_WIN32) && defined(XYZ_VEL)
  #undef XYZ_VEL
#endif
#if defined(_WIN32) && defined(XYZ_ACC)
  #undef XYZ_ACC
#endif
#if defined(_WIN32) && defined(XYZ_POS_VEL)
  #undef XYZ_POS_VEL
#endif
#if defined(_WIN32) && defined(TRAJECTORY)
  #undef TRAJECTORY
#endif
#if defined(_WIN32) && defined(ENU_FRAME)
  #undef ENU_FRAME
#endif
#if defined(_WIN32) && defined(BODY_FRAME)
  #undef BODY_FRAME
#endif

  enum {
    XYZ_POS = 0u,
    XY_POS_Z_VEL = 1u,
    XY_VEL_Z_POS = 2u,
    XYZ_VEL = 3u,
    XYZ_ACC = 4u,
    XYZ_POS_VEL = 5u,
    TRAJECTORY = 6u,
    ENU_FRAME = 0u,
    BODY_FRAME = 1u,
  };


  typedef boost::shared_ptr< ::drone_msgs::PositionReference_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::drone_msgs::PositionReference_<ContainerAllocator> const> ConstPtr;

}; // struct PositionReference_

typedef ::drone_msgs::PositionReference_<std::allocator<void> > PositionReference;

typedef boost::shared_ptr< ::drone_msgs::PositionReference > PositionReferencePtr;
typedef boost::shared_ptr< ::drone_msgs::PositionReference const> PositionReferenceConstPtr;

// constants requiring out of line definition

   

   

   

   

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::drone_msgs::PositionReference_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::drone_msgs::PositionReference_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::drone_msgs::PositionReference_<ContainerAllocator1> & lhs, const ::drone_msgs::PositionReference_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.Move_mode == rhs.Move_mode &&
    lhs.Move_frame == rhs.Move_frame &&
    lhs.time_from_start == rhs.time_from_start &&
    lhs.position_ref == rhs.position_ref &&
    lhs.velocity_ref == rhs.velocity_ref &&
    lhs.acceleration_ref == rhs.acceleration_ref &&
    lhs.Yaw_Rate_Mode == rhs.Yaw_Rate_Mode &&
    lhs.yaw_ref == rhs.yaw_ref &&
    lhs.yaw_rate_ref == rhs.yaw_rate_ref &&
    lhs.bspline == rhs.bspline;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::drone_msgs::PositionReference_<ContainerAllocator1> & lhs, const ::drone_msgs::PositionReference_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace drone_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::drone_msgs::PositionReference_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::drone_msgs::PositionReference_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::drone_msgs::PositionReference_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::drone_msgs::PositionReference_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::drone_msgs::PositionReference_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::drone_msgs::PositionReference_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::drone_msgs::PositionReference_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d029a5a9568f27a7cd91ef81b8f15a11";
  }

  static const char* value(const ::drone_msgs::PositionReference_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd029a5a9568f27a7ULL;
  static const uint64_t static_value2 = 0xcd91ef81b8f15a11ULL;
};

template<class ContainerAllocator>
struct DataType< ::drone_msgs::PositionReference_<ContainerAllocator> >
{
  static const char* value()
  {
    return "drone_msgs/PositionReference";
  }

  static const char* value(const ::drone_msgs::PositionReference_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::drone_msgs::PositionReference_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"\n"
"## Setpoint position reference for PX4 Control\n"
"\n"
"## Setpoint Mode\n"
"uint8 Move_mode\n"
"\n"
"uint8 XYZ_POS      = 0  ##0b00\n"
"uint8 XY_POS_Z_VEL = 1  ##0b01\n"
"uint8 XY_VEL_Z_POS = 2  ##0b10\n"
"uint8 XYZ_VEL = 3       ##0b11\n"
"uint8 XYZ_ACC = 4\n"
"uint8 XYZ_POS_VEL   = 5  \n"
"uint8 TRAJECTORY   = 6\n"
"\n"
"## Reference Frame\n"
"uint8 Move_frame\n"
"\n"
"uint8 ENU_FRAME  = 0\n"
"uint8 BODY_FRAME = 1\n"
"\n"
"\n"
"\n"
"## Tracking life\n"
"float32 time_from_start          ## [s]\n"
"\n"
"float32[3] position_ref          ## [m]\n"
"float32[3] velocity_ref          ## [m/s]\n"
"float32[3] acceleration_ref      ## [m/s^2]\n"
"\n"
"bool Yaw_Rate_Mode                      ## True 代表控制偏航角速率\n"
"float32 yaw_ref                  ## [rad]\n"
"float32 yaw_rate_ref             ## [rad/s] \n"
"\n"
"Bspline bspline\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: drone_msgs/Bspline\n"
"int32 order                 ## \n"
"int64 traj_id               ## id of trajecotry\n"
"float64[] knots             ## knots list\n"
"geometry_msgs/Point[] pts   ## control points list\n"
"time start_time             ## time stamp\n"
"\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::drone_msgs::PositionReference_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::drone_msgs::PositionReference_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.Move_mode);
      stream.next(m.Move_frame);
      stream.next(m.time_from_start);
      stream.next(m.position_ref);
      stream.next(m.velocity_ref);
      stream.next(m.acceleration_ref);
      stream.next(m.Yaw_Rate_Mode);
      stream.next(m.yaw_ref);
      stream.next(m.yaw_rate_ref);
      stream.next(m.bspline);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PositionReference_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::drone_msgs::PositionReference_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::drone_msgs::PositionReference_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "Move_mode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.Move_mode);
    s << indent << "Move_frame: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.Move_frame);
    s << indent << "time_from_start: ";
    Printer<float>::stream(s, indent + "  ", v.time_from_start);
    s << indent << "position_ref[]" << std::endl;
    for (size_t i = 0; i < v.position_ref.size(); ++i)
    {
      s << indent << "  position_ref[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.position_ref[i]);
    }
    s << indent << "velocity_ref[]" << std::endl;
    for (size_t i = 0; i < v.velocity_ref.size(); ++i)
    {
      s << indent << "  velocity_ref[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.velocity_ref[i]);
    }
    s << indent << "acceleration_ref[]" << std::endl;
    for (size_t i = 0; i < v.acceleration_ref.size(); ++i)
    {
      s << indent << "  acceleration_ref[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.acceleration_ref[i]);
    }
    s << indent << "Yaw_Rate_Mode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.Yaw_Rate_Mode);
    s << indent << "yaw_ref: ";
    Printer<float>::stream(s, indent + "  ", v.yaw_ref);
    s << indent << "yaw_rate_ref: ";
    Printer<float>::stream(s, indent + "  ", v.yaw_rate_ref);
    s << indent << "bspline: ";
    s << std::endl;
    Printer< ::drone_msgs::Bspline_<ContainerAllocator> >::stream(s, indent + "  ", v.bspline);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DRONE_MSGS_MESSAGE_POSITIONREFERENCE_H
