# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from drone_msgs/ControlCommand.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import drone_msgs.msg
import genpy
import geometry_msgs.msg
import std_msgs.msg

class ControlCommand(genpy.Message):
  _md5sum = "969640b304f3a446799efdd5c334e9b7"
  _type = "drone_msgs/ControlCommand"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """std_msgs/Header header

## ID should increased self
uint32 Command_ID

string source

uint8 Mode
# enum
uint8 Idle=0
uint8 Takeoff=1
uint8 Hold=2
uint8 Land=3
uint8 Move=4
uint8 Disarm=5
uint8 Attitude=6
uint8 AttitudeRate=7
uint8 Rate=8

## Setpoint Reference
PositionReference Reference_State
AttitudeReference Attitude_sp

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id

================================================================================
MSG: drone_msgs/PositionReference
std_msgs/Header header

## Setpoint position reference for PX4 Control

## Setpoint Mode
uint8 Move_mode

uint8 XYZ_POS      = 0  ##0b00
uint8 XY_POS_Z_VEL = 1  ##0b01
uint8 XY_VEL_Z_POS = 2  ##0b10
uint8 XYZ_VEL = 3       ##0b11
uint8 XYZ_ACC = 4
uint8 XYZ_POS_VEL   = 5  
uint8 TRAJECTORY   = 6

## Reference Frame
uint8 Move_frame

uint8 ENU_FRAME  = 0
uint8 BODY_FRAME = 1



## Tracking life
float32 time_from_start          ## [s]

float32[3] position_ref          ## [m]
float32[3] velocity_ref          ## [m/s]
float32[3] acceleration_ref      ## [m/s^2]

bool Yaw_Rate_Mode                      ## True 代表控制偏航角速率
float32 yaw_ref                  ## [rad]
float32 yaw_rate_ref             ## [rad/s] 

Bspline bspline
================================================================================
MSG: drone_msgs/Bspline
int32 order                 ## 
int64 traj_id               ## id of trajecotry
float64[] knots             ## knots list
geometry_msgs/Point[] pts   ## control points list
time start_time             ## time stamp


================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: drone_msgs/AttitudeReference
std_msgs/Header header

## Setpoint Attitude + T
float32[3] thrust_sp                   ## Single Rotor Thrust setpoint
float32 collective_accel               ## [m/s^2] Axis Body_Z Collective accel septoint
float32[3] desired_attitude            ## [rad] Eurler angle setpoint
geometry_msgs/Quaternion desired_att_q ## quat setpoint
geometry_msgs/Vector3 body_rate  ## [rad/s]

================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w

================================================================================
MSG: geometry_msgs/Vector3
# This represents a vector in free space. 
# It is only meant to represent a direction. Therefore, it does not
# make sense to apply a translation to it (e.g., when applying a 
# generic rigid transformation to a Vector3, tf2 will only apply the
# rotation). If you want your data to be translatable too, use the
# geometry_msgs/Point message instead.

float64 x
float64 y
float64 z"""
  # Pseudo-constants
  Idle = 0
  Takeoff = 1
  Hold = 2
  Land = 3
  Move = 4
  Disarm = 5
  Attitude = 6
  AttitudeRate = 7
  Rate = 8

  __slots__ = ['header','Command_ID','source','Mode','Reference_State','Attitude_sp']
  _slot_types = ['std_msgs/Header','uint32','string','uint8','drone_msgs/PositionReference','drone_msgs/AttitudeReference']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,Command_ID,source,Mode,Reference_State,Attitude_sp

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ControlCommand, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.Command_ID is None:
        self.Command_ID = 0
      if self.source is None:
        self.source = ''
      if self.Mode is None:
        self.Mode = 0
      if self.Reference_State is None:
        self.Reference_State = drone_msgs.msg.PositionReference()
      if self.Attitude_sp is None:
        self.Attitude_sp = drone_msgs.msg.AttitudeReference()
    else:
      self.header = std_msgs.msg.Header()
      self.Command_ID = 0
      self.source = ''
      self.Mode = 0
      self.Reference_State = drone_msgs.msg.PositionReference()
      self.Attitude_sp = drone_msgs.msg.AttitudeReference()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.Command_ID
      buff.write(_get_struct_I().pack(_x))
      _x = self.source
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_B3I().pack(_x.Mode, _x.Reference_State.header.seq, _x.Reference_State.header.stamp.secs, _x.Reference_State.header.stamp.nsecs))
      _x = self.Reference_State.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2Bf().pack(_x.Reference_State.Move_mode, _x.Reference_State.Move_frame, _x.Reference_State.time_from_start))
      buff.write(_get_struct_3f().pack(*self.Reference_State.position_ref))
      buff.write(_get_struct_3f().pack(*self.Reference_State.velocity_ref))
      buff.write(_get_struct_3f().pack(*self.Reference_State.acceleration_ref))
      _x = self
      buff.write(_get_struct_B2fiq().pack(_x.Reference_State.Yaw_Rate_Mode, _x.Reference_State.yaw_ref, _x.Reference_State.yaw_rate_ref, _x.Reference_State.bspline.order, _x.Reference_State.bspline.traj_id))
      length = len(self.Reference_State.bspline.knots)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(struct.Struct(pattern).pack(*self.Reference_State.bspline.knots))
      length = len(self.Reference_State.bspline.pts)
      buff.write(_struct_I.pack(length))
      for val1 in self.Reference_State.bspline.pts:
        _x = val1
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
      _x = self
      buff.write(_get_struct_5I().pack(_x.Reference_State.bspline.start_time.secs, _x.Reference_State.bspline.start_time.nsecs, _x.Attitude_sp.header.seq, _x.Attitude_sp.header.stamp.secs, _x.Attitude_sp.header.stamp.nsecs))
      _x = self.Attitude_sp.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      buff.write(_get_struct_3f().pack(*self.Attitude_sp.thrust_sp))
      _x = self.Attitude_sp.collective_accel
      buff.write(_get_struct_f().pack(_x))
      buff.write(_get_struct_3f().pack(*self.Attitude_sp.desired_attitude))
      _x = self
      buff.write(_get_struct_7d().pack(_x.Attitude_sp.desired_att_q.x, _x.Attitude_sp.desired_att_q.y, _x.Attitude_sp.desired_att_q.z, _x.Attitude_sp.desired_att_q.w, _x.Attitude_sp.body_rate.x, _x.Attitude_sp.body_rate.y, _x.Attitude_sp.body_rate.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.Reference_State is None:
        self.Reference_State = drone_msgs.msg.PositionReference()
      if self.Attitude_sp is None:
        self.Attitude_sp = drone_msgs.msg.AttitudeReference()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      start = end
      end += 4
      (self.Command_ID,) = _get_struct_I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.source = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.source = str[start:end]
      _x = self
      start = end
      end += 13
      (_x.Mode, _x.Reference_State.header.seq, _x.Reference_State.header.stamp.secs, _x.Reference_State.header.stamp.nsecs,) = _get_struct_B3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.Reference_State.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.Reference_State.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 6
      (_x.Reference_State.Move_mode, _x.Reference_State.Move_frame, _x.Reference_State.time_from_start,) = _get_struct_2Bf().unpack(str[start:end])
      start = end
      end += 12
      self.Reference_State.position_ref = _get_struct_3f().unpack(str[start:end])
      start = end
      end += 12
      self.Reference_State.velocity_ref = _get_struct_3f().unpack(str[start:end])
      start = end
      end += 12
      self.Reference_State.acceleration_ref = _get_struct_3f().unpack(str[start:end])
      _x = self
      start = end
      end += 21
      (_x.Reference_State.Yaw_Rate_Mode, _x.Reference_State.yaw_ref, _x.Reference_State.yaw_rate_ref, _x.Reference_State.bspline.order, _x.Reference_State.bspline.traj_id,) = _get_struct_B2fiq().unpack(str[start:end])
      self.Reference_State.Yaw_Rate_Mode = bool(self.Reference_State.Yaw_Rate_Mode)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.Reference_State.bspline.knots = s.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.Reference_State.bspline.pts = []
      for i in range(0, length):
        val1 = geometry_msgs.msg.Point()
        _x = val1
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        self.Reference_State.bspline.pts.append(val1)
      _x = self
      start = end
      end += 20
      (_x.Reference_State.bspline.start_time.secs, _x.Reference_State.bspline.start_time.nsecs, _x.Attitude_sp.header.seq, _x.Attitude_sp.header.stamp.secs, _x.Attitude_sp.header.stamp.nsecs,) = _get_struct_5I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.Attitude_sp.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.Attitude_sp.header.frame_id = str[start:end]
      start = end
      end += 12
      self.Attitude_sp.thrust_sp = _get_struct_3f().unpack(str[start:end])
      start = end
      end += 4
      (self.Attitude_sp.collective_accel,) = _get_struct_f().unpack(str[start:end])
      start = end
      end += 12
      self.Attitude_sp.desired_attitude = _get_struct_3f().unpack(str[start:end])
      _x = self
      start = end
      end += 56
      (_x.Attitude_sp.desired_att_q.x, _x.Attitude_sp.desired_att_q.y, _x.Attitude_sp.desired_att_q.z, _x.Attitude_sp.desired_att_q.w, _x.Attitude_sp.body_rate.x, _x.Attitude_sp.body_rate.y, _x.Attitude_sp.body_rate.z,) = _get_struct_7d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.Command_ID
      buff.write(_get_struct_I().pack(_x))
      _x = self.source
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_B3I().pack(_x.Mode, _x.Reference_State.header.seq, _x.Reference_State.header.stamp.secs, _x.Reference_State.header.stamp.nsecs))
      _x = self.Reference_State.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2Bf().pack(_x.Reference_State.Move_mode, _x.Reference_State.Move_frame, _x.Reference_State.time_from_start))
      buff.write(self.Reference_State.position_ref.tostring())
      buff.write(self.Reference_State.velocity_ref.tostring())
      buff.write(self.Reference_State.acceleration_ref.tostring())
      _x = self
      buff.write(_get_struct_B2fiq().pack(_x.Reference_State.Yaw_Rate_Mode, _x.Reference_State.yaw_ref, _x.Reference_State.yaw_rate_ref, _x.Reference_State.bspline.order, _x.Reference_State.bspline.traj_id))
      length = len(self.Reference_State.bspline.knots)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(self.Reference_State.bspline.knots.tostring())
      length = len(self.Reference_State.bspline.pts)
      buff.write(_struct_I.pack(length))
      for val1 in self.Reference_State.bspline.pts:
        _x = val1
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
      _x = self
      buff.write(_get_struct_5I().pack(_x.Reference_State.bspline.start_time.secs, _x.Reference_State.bspline.start_time.nsecs, _x.Attitude_sp.header.seq, _x.Attitude_sp.header.stamp.secs, _x.Attitude_sp.header.stamp.nsecs))
      _x = self.Attitude_sp.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      buff.write(self.Attitude_sp.thrust_sp.tostring())
      _x = self.Attitude_sp.collective_accel
      buff.write(_get_struct_f().pack(_x))
      buff.write(self.Attitude_sp.desired_attitude.tostring())
      _x = self
      buff.write(_get_struct_7d().pack(_x.Attitude_sp.desired_att_q.x, _x.Attitude_sp.desired_att_q.y, _x.Attitude_sp.desired_att_q.z, _x.Attitude_sp.desired_att_q.w, _x.Attitude_sp.body_rate.x, _x.Attitude_sp.body_rate.y, _x.Attitude_sp.body_rate.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.Reference_State is None:
        self.Reference_State = drone_msgs.msg.PositionReference()
      if self.Attitude_sp is None:
        self.Attitude_sp = drone_msgs.msg.AttitudeReference()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      start = end
      end += 4
      (self.Command_ID,) = _get_struct_I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.source = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.source = str[start:end]
      _x = self
      start = end
      end += 13
      (_x.Mode, _x.Reference_State.header.seq, _x.Reference_State.header.stamp.secs, _x.Reference_State.header.stamp.nsecs,) = _get_struct_B3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.Reference_State.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.Reference_State.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 6
      (_x.Reference_State.Move_mode, _x.Reference_State.Move_frame, _x.Reference_State.time_from_start,) = _get_struct_2Bf().unpack(str[start:end])
      start = end
      end += 12
      self.Reference_State.position_ref = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=3)
      start = end
      end += 12
      self.Reference_State.velocity_ref = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=3)
      start = end
      end += 12
      self.Reference_State.acceleration_ref = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=3)
      _x = self
      start = end
      end += 21
      (_x.Reference_State.Yaw_Rate_Mode, _x.Reference_State.yaw_ref, _x.Reference_State.yaw_rate_ref, _x.Reference_State.bspline.order, _x.Reference_State.bspline.traj_id,) = _get_struct_B2fiq().unpack(str[start:end])
      self.Reference_State.Yaw_Rate_Mode = bool(self.Reference_State.Yaw_Rate_Mode)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.Reference_State.bspline.knots = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.Reference_State.bspline.pts = []
      for i in range(0, length):
        val1 = geometry_msgs.msg.Point()
        _x = val1
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        self.Reference_State.bspline.pts.append(val1)
      _x = self
      start = end
      end += 20
      (_x.Reference_State.bspline.start_time.secs, _x.Reference_State.bspline.start_time.nsecs, _x.Attitude_sp.header.seq, _x.Attitude_sp.header.stamp.secs, _x.Attitude_sp.header.stamp.nsecs,) = _get_struct_5I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.Attitude_sp.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.Attitude_sp.header.frame_id = str[start:end]
      start = end
      end += 12
      self.Attitude_sp.thrust_sp = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=3)
      start = end
      end += 4
      (self.Attitude_sp.collective_accel,) = _get_struct_f().unpack(str[start:end])
      start = end
      end += 12
      self.Attitude_sp.desired_attitude = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=3)
      _x = self
      start = end
      end += 56
      (_x.Attitude_sp.desired_att_q.x, _x.Attitude_sp.desired_att_q.y, _x.Attitude_sp.desired_att_q.z, _x.Attitude_sp.desired_att_q.w, _x.Attitude_sp.body_rate.x, _x.Attitude_sp.body_rate.y, _x.Attitude_sp.body_rate.z,) = _get_struct_7d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2Bf = None
def _get_struct_2Bf():
    global _struct_2Bf
    if _struct_2Bf is None:
        _struct_2Bf = struct.Struct("<2Bf")
    return _struct_2Bf
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_3d = None
def _get_struct_3d():
    global _struct_3d
    if _struct_3d is None:
        _struct_3d = struct.Struct("<3d")
    return _struct_3d
_struct_3f = None
def _get_struct_3f():
    global _struct_3f
    if _struct_3f is None:
        _struct_3f = struct.Struct("<3f")
    return _struct_3f
_struct_5I = None
def _get_struct_5I():
    global _struct_5I
    if _struct_5I is None:
        _struct_5I = struct.Struct("<5I")
    return _struct_5I
_struct_7d = None
def _get_struct_7d():
    global _struct_7d
    if _struct_7d is None:
        _struct_7d = struct.Struct("<7d")
    return _struct_7d
_struct_B2fiq = None
def _get_struct_B2fiq():
    global _struct_B2fiq
    if _struct_B2fiq is None:
        _struct_B2fiq = struct.Struct("<B2fiq")
    return _struct_B2fiq
_struct_B3I = None
def _get_struct_B3I():
    global _struct_B3I
    if _struct_B3I is None:
        _struct_B3I = struct.Struct("<B3I")
    return _struct_B3I
_struct_f = None
def _get_struct_f():
    global _struct_f
    if _struct_f is None:
        _struct_f = struct.Struct("<f")
    return _struct_f
