set(_CATKIN_CURRENT_PACKAGE "simulation_gazebo")
set(simulation_gazebo_VERSION "0.0.0")
set(simulation_gazebo_MAINTAINER "ze wang <w407022008@gmail.com>")
set(simulation_gazebo_PACKAGE_FORMAT "2")
set(simulation_gazebo_BUILD_DEPENDS "message_generation" "message_runtime" "std_msgs" "gazebo_ros" "roscpp" "rospy" "camera_info_manager" "geometry_msgs")
set(simulation_gazebo_BUILD_EXPORT_DEPENDS "message_runtime" "std_msgs" "gazebo_ros" "roscpp" "rospy" "camera_info_manager" "geometry_msgs")
set(simulation_gazebo_BUILDTOOL_DEPENDS "catkin")
set(simulation_gazebo_BUILDTOOL_EXPORT_DEPENDS )
set(simulation_gazebo_EXEC_DEPENDS "depth_image_proc" "urdf" "xacro" "message_runtime" "std_msgs" "gazebo_ros" "roscpp" "rospy" "camera_info_manager" "geometry_msgs")
set(simulation_gazebo_RUN_DEPENDS "depth_image_proc" "urdf" "xacro" "message_runtime" "std_msgs" "gazebo_ros" "roscpp" "rospy" "camera_info_manager" "geometry_msgs")
set(simulation_gazebo_TEST_DEPENDS "rostest")
set(simulation_gazebo_DOC_DEPENDS )
set(simulation_gazebo_URL_WEBSITE "")
set(simulation_gazebo_URL_BUGTRACKER "")
set(simulation_gazebo_URL_REPOSITORY "")
set(simulation_gazebo_DEPRECATED "")