# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from quadrotor_msgs/ControlCommand.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import genpy
import geometry_msgs.msg
import std_msgs.msg

class ControlCommand(genpy.Message):
  _md5sum = "a1918a34164f6647c898e4d55efbfcef"
  _type = "quadrotor_msgs/ControlCommand"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """# Quadrotor control command

# control mode enums
uint8 NONE=0
uint8 ATTITUDE=1
uint8 BODY_RATES=2
uint8 ANGULAR_ACCELERATIONS=3
uint8 ROTOR_THRUSTS=4

Header header

# Control mode as defined above
uint8 control_mode

# Flag whether controller is allowed to arm
bool armed

# Time at which this command should be executed
time expected_execution_time

# Orientation of the body frame with respect to the world frame [-]
geometry_msgs/Quaternion orientation

# Body rates in body frame [rad/s]
# Note that in ATTITUDE mode the x-y-bodyrates are only feed forward terms 
# computed from a reference trajectory
# Also in ATTITUDE mode, the z-bodyrate has to be from feedback control
geometry_msgs/Vector3 bodyrates

# Angular accelerations in body frame [rad/s^2]
geometry_msgs/Vector3 angular_accelerations

# Collective mass normalized thrust [m/s^2]
float64 collective_thrust

# Single rotor thrusts [N]
# These are only considered in the ROTOR_THRUSTS control mode
float64[] rotor_thrusts

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id

================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w

================================================================================
MSG: geometry_msgs/Vector3
# This represents a vector in free space. 
# It is only meant to represent a direction. Therefore, it does not
# make sense to apply a translation to it (e.g., when applying a 
# generic rigid transformation to a Vector3, tf2 will only apply the
# rotation). If you want your data to be translatable too, use the
# geometry_msgs/Point message instead.

float64 x
float64 y
float64 z"""
  # Pseudo-constants
  NONE = 0
  ATTITUDE = 1
  BODY_RATES = 2
  ANGULAR_ACCELERATIONS = 3
  ROTOR_THRUSTS = 4

  __slots__ = ['header','control_mode','armed','expected_execution_time','orientation','bodyrates','angular_accelerations','collective_thrust','rotor_thrusts']
  _slot_types = ['std_msgs/Header','uint8','bool','time','geometry_msgs/Quaternion','geometry_msgs/Vector3','geometry_msgs/Vector3','float64','float64[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,control_mode,armed,expected_execution_time,orientation,bodyrates,angular_accelerations,collective_thrust,rotor_thrusts

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ControlCommand, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.control_mode is None:
        self.control_mode = 0
      if self.armed is None:
        self.armed = False
      if self.expected_execution_time is None:
        self.expected_execution_time = genpy.Time()
      if self.orientation is None:
        self.orientation = geometry_msgs.msg.Quaternion()
      if self.bodyrates is None:
        self.bodyrates = geometry_msgs.msg.Vector3()
      if self.angular_accelerations is None:
        self.angular_accelerations = geometry_msgs.msg.Vector3()
      if self.collective_thrust is None:
        self.collective_thrust = 0.
      if self.rotor_thrusts is None:
        self.rotor_thrusts = []
    else:
      self.header = std_msgs.msg.Header()
      self.control_mode = 0
      self.armed = False
      self.expected_execution_time = genpy.Time()
      self.orientation = geometry_msgs.msg.Quaternion()
      self.bodyrates = geometry_msgs.msg.Vector3()
      self.angular_accelerations = geometry_msgs.msg.Vector3()
      self.collective_thrust = 0.
      self.rotor_thrusts = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2B2I11d().pack(_x.control_mode, _x.armed, _x.expected_execution_time.secs, _x.expected_execution_time.nsecs, _x.orientation.x, _x.orientation.y, _x.orientation.z, _x.orientation.w, _x.bodyrates.x, _x.bodyrates.y, _x.bodyrates.z, _x.angular_accelerations.x, _x.angular_accelerations.y, _x.angular_accelerations.z, _x.collective_thrust))
      length = len(self.rotor_thrusts)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(struct.Struct(pattern).pack(*self.rotor_thrusts))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.expected_execution_time is None:
        self.expected_execution_time = genpy.Time()
      if self.orientation is None:
        self.orientation = geometry_msgs.msg.Quaternion()
      if self.bodyrates is None:
        self.bodyrates = geometry_msgs.msg.Vector3()
      if self.angular_accelerations is None:
        self.angular_accelerations = geometry_msgs.msg.Vector3()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 98
      (_x.control_mode, _x.armed, _x.expected_execution_time.secs, _x.expected_execution_time.nsecs, _x.orientation.x, _x.orientation.y, _x.orientation.z, _x.orientation.w, _x.bodyrates.x, _x.bodyrates.y, _x.bodyrates.z, _x.angular_accelerations.x, _x.angular_accelerations.y, _x.angular_accelerations.z, _x.collective_thrust,) = _get_struct_2B2I11d().unpack(str[start:end])
      self.armed = bool(self.armed)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.rotor_thrusts = s.unpack(str[start:end])
      self.expected_execution_time.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2B2I11d().pack(_x.control_mode, _x.armed, _x.expected_execution_time.secs, _x.expected_execution_time.nsecs, _x.orientation.x, _x.orientation.y, _x.orientation.z, _x.orientation.w, _x.bodyrates.x, _x.bodyrates.y, _x.bodyrates.z, _x.angular_accelerations.x, _x.angular_accelerations.y, _x.angular_accelerations.z, _x.collective_thrust))
      length = len(self.rotor_thrusts)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(self.rotor_thrusts.tostring())
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.expected_execution_time is None:
        self.expected_execution_time = genpy.Time()
      if self.orientation is None:
        self.orientation = geometry_msgs.msg.Quaternion()
      if self.bodyrates is None:
        self.bodyrates = geometry_msgs.msg.Vector3()
      if self.angular_accelerations is None:
        self.angular_accelerations = geometry_msgs.msg.Vector3()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 98
      (_x.control_mode, _x.armed, _x.expected_execution_time.secs, _x.expected_execution_time.nsecs, _x.orientation.x, _x.orientation.y, _x.orientation.z, _x.orientation.w, _x.bodyrates.x, _x.bodyrates.y, _x.bodyrates.z, _x.angular_accelerations.x, _x.angular_accelerations.y, _x.angular_accelerations.z, _x.collective_thrust,) = _get_struct_2B2I11d().unpack(str[start:end])
      self.armed = bool(self.armed)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.rotor_thrusts = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
      self.expected_execution_time.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2B2I11d = None
def _get_struct_2B2I11d():
    global _struct_2B2I11d
    if _struct_2B2I11d is None:
        _struct_2B2I11d = struct.Struct("<2B2I11d")
    return _struct_2B2I11d
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
