set(_CATKIN_CURRENT_PACKAGE "common")
set(common_VERSION "0.0.0")
set(common_MAINTAINER "ze wang <w407022008@gmail.com>")
set(common_PACKAGE_FORMAT "2")
set(common_BUILD_DEPENDS "message_generation" "std_msgs")
set(common_BUILD_EXPORT_DEPENDS "std_msgs")
set(common_BUILDTOOL_DEPENDS "catkin")
set(common_BUILDTOOL_EXPORT_DEPENDS )
set(common_EXEC_DEPENDS "message_runtime" "std_msgs")
set(common_RUN_DEPENDS "message_runtime" "std_msgs")
set(common_TEST_DEPENDS )
set(common_DOC_DEPENDS )
set(common_URL_WEBSITE "")
set(common_URL_BUGTRACKER "")
set(common_URL_REPOSITORY "")
set(common_DEPRECATED "")