set(_CATKIN_CURRENT_PACKAGE "active_perception")
set(active_perception_VERSION "0.0.0")
set(active_perception_MAINTAINER "boboyu <boboyu@todo.todo>")
set(active_perception_PACKAGE_FORMAT "2")
set(active_perception_BUILD_DEPENDS "roscpp" "rospy" "std_msgs" "plan_env" "bspline" "path_searching")
set(active_perception_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs" "plan_env" "bspline" "path_searching")
set(active_perception_BUILDTOOL_DEPENDS "catkin")
set(active_perception_BUILDTOOL_EXPORT_DEPENDS )
set(active_perception_EXEC_DEPENDS "roscpp" "rospy" "std_msgs" "plan_env" "bspline" "path_searching")
set(active_perception_RUN_DEPENDS "roscpp" "rospy" "std_msgs" "plan_env" "bspline" "path_searching")
set(active_perception_TEST_DEPENDS )
set(active_perception_DOC_DEPENDS )
set(active_perception_URL_WEBSITE "")
set(active_perception_URL_BUGTRACKER "")
set(active_perception_URL_REPOSITORY "")
set(active_perception_DEPRECATED "")