set(_CATKIN_CURRENT_PACKAGE "quadrotor_msgs")
set(quadrotor_msgs_VERSION "0.0.0")
set(quadrotor_msgs_MAINTAINER "Matthias Faessler <faessler@ifi.uzh.ch>")
set(quadrotor_msgs_PACKAGE_FORMAT "2")
set(quadrotor_msgs_BUILD_DEPENDS "geometry_msgs" "message_generation" "nav_msgs" "std_msgs")
set(quadrotor_msgs_BUILD_EXPORT_DEPENDS )
set(quadrotor_msgs_BUILDTOOL_DEPENDS "catkin" "catkin_simple")
set(quadrotor_msgs_BUILDTOOL_EXPORT_DEPENDS )
set(quadrotor_msgs_EXEC_DEPENDS )
set(quadrotor_msgs_RUN_DEPENDS )
set(quadrotor_msgs_TEST_DEPENDS )
set(quadrotor_msgs_DOC_DEPENDS )
set(quadrotor_msgs_URL_WEBSITE "")
set(quadrotor_msgs_URL_BUGTRACKER "")
set(quadrotor_msgs_URL_REPOSITORY "")
set(quadrotor_msgs_DEPRECATED "")